"""add userpreference table

Revision ID: 699593984234
Revises: a1b2c3d4e5f6
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '699593984234'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
